# lightning.pytorch==2.5.3
tracking_metric: validation_accuracy
tracking_metric_mode: max
optimizer: null
lr_scheduler: null
seed_everything: false
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger:
    class_path: lightning.pytorch.loggers.CSVLogger
    init_args:
      save_dir: /workspaces/experimental-wsd/lightning_logs
      name: small_usas_test_model
      version: null
      prefix: ''
      flush_logs_every_n_steps: 100
  callbacks:
    - class_path: "lightning.pytorch.callbacks.EarlyStopping"
      init_args:
        monitor: ${tracking_metric}
        mode: ${tracking_metric_mode}
        check_finite: true
        patience: 5
        verbose: true
        strict: true
    - class_path: "lightning.pytorch.callbacks.ModelCheckpoint"
      init_args:
        monitor: ${tracking_metric}
        mode: ${tracking_metric_mode}
        save_top_k: 1
        save_last: true
        filename: "best-model-epoch-{epoch}"
    - class_path: "lightning.pytorch.callbacks.LearningRateMonitor"
      init_args:
        logging_interval: "step"
  fast_dev_run: false
  max_epochs: 20
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: 0.1
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 2
  gradient_clip_val: null
  gradient_clip_algorithm: norm
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
  model_registry: null
model:
  base_model_name: "jhu-clsp/ettin-encoder-17m"
  freeze_base_model: false
  number_transformer_encoder_layers: 0
  add_scalar_mixer: false
  scalar_mix_layer_norm: true
  transformer_encoder_hidden_dim: 512
  transformer_encoder_num_heads: 8
  batch_first: true
  learning_rate: 2.0e-05
  weight_decay: 0.01
  use_scheduler: false
  fraction_of_warm_up_steps: 0.1
  scheduler_frequency: 1
data:
  tokenizer_kwargs:
    add_prefix_space: true
  batch_size: 32
  num_cpus_pre_processing: 10
  num_dataloader_cpus: 12
  overwrite_all_pre_processed_data: false
  attention_pad_id: 0